"""add users table

Revision ID: 863b7f91f18a
Revises: 
Create Date: 2019-08-08 22:40:47.073653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863b7f91f18a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('image_file', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('aadhar', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('dob', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhar'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_gender'), 'user', ['gender'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_gender'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
